server:
  port: 8882

spring:
  application:
    name: pub2
  rabbitmq:
    host: localhost
    port: 5672
    stomp-port: 61613
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 1

jwt:
  issuer: akuzmenko
  secret: ca8EjH6NzLdS1pOyadW4Yt88RbZ2lMwFvj

cache:
  host: localhost
  port: 6379
  password: password